# Generated by Django 2.1.7 on 2019-04-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('accounts', '0003_auto_20190417_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.ManyToManyField(blank=True, null=True, to='batches.batches'),
        ),
    ]
