# Generated by Django 2.1.7 on 2019-04-17 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('accounts', '0004_user_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='batch',
        ),
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batches.batches'),
        ),
    ]
