# Generated by Django 2.1.7 on 2019-04-17 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190417_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batches.batches'),
        ),
    ]
