# Generated by Django 2.1.7 on 2019-05-22 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=140)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mcqs/images/%Y/%m/$D/')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=270)),
                ('answer', models.CharField(max_length=140)),
                ('q_image', models.ImageField(blank=True, null=True, upload_to='mcqs/images/%Y/%m/$D/')),
                ('a_image', models.ImageField(blank=True, null=True, upload_to='mcqs/images/%Y/%m/$D/')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=270)),
                ('option_one', models.CharField(blank=True, max_length=270, null=True)),
                ('option_two', models.CharField(blank=True, max_length=270, null=True)),
                ('option_three', models.CharField(blank=True, max_length=270, null=True)),
                ('option_four', models.CharField(blank=True, max_length=270, null=True)),
                ('answer', models.CharField(max_length=140)),
                ('q_image', models.ImageField(blank=True, null=True, upload_to='mcqs/images/%Y/%m/$D/')),
                ('a_image', models.ImageField(blank=True, null=True, upload_to='mcqs/images/%Y/%m/$D/')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.subject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mcq',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcq.Topic'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcq.Topic'),
        ),
        migrations.AddField(
            model_name='fact',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcq.Topic'),
        ),
    ]
