# Generated by Django 2.2.1 on 2019-05-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_auto_20190531_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.CharField(max_length=2540),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.CharField(max_length=5270),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question',
            field=models.CharField(max_length=1270),
        ),
    ]
