# Generated by Django 2.2.1 on 2019-05-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190524_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusnews',
            name='heading',
            field=models.CharField(max_length=40),
        ),
    ]
